import Head from 'next/head';
import { Poppins } from '@next/font/google';
import type { AppProps } from 'next/app';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '../styles/globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Youthfully Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`min-h-screen ${poppins.className}`}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}
